[project]
name = "wikimovies"
version = "0.1.0"
description = "A Semantic search for movies in wikipedia website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scrapy>=2.13.2",
]
